name: generate-debs

on: push

jobs:
  build_humble:
    runs-on: ubuntu-22.04
    steps:
      - uses: jspricke/ros-deb-builder-action@rosotest
        with:
          DEB_DISTRO: jammy
          ROS_DISTRO: humble
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SQUASH_HISTORY: true

  build_rolling:
    runs-on: ubuntu-22.04
    steps:
      - uses: jspricke/ros-deb-builder-action@rosotest
        with:
          DEB_DISTRO: jammy
          ROS_DISTRO: rolling
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SQUASH_HISTORY: true
